import time 
a,b,c=12,15,2022 
print("---Date---")
print(a,b,c,sep="/")
print()
print("---Another Date---")
print(a,b,c,sep="-")
print()
print("---Time----")
print(a,b,c,sep=":")
print()
print("---Digital time---")
print(a,b,c,sep="::")
print()
print("---Amount in INR---")
print(a,b,c,sep=",")
print()
time.sleep(2)
print("End of an application ...")
